<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Authors>aicd0</Authors>
		<Description>Comic Reader UWP SDK</Description>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageId>ComicReaderUWP.SDK</PackageId>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
		<Version>1.5.1.0</Version>
		<WarningsNotAsErrors>NU1903</WarningsNotAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.250909003" />
	</ItemGroup>

</Project>
